const COUNTRY_FLAGS: Record<string, string> = {
  // FIFA World Cup 2026 - equipos
  Argentina: "🇦🇷",
  Canadá: "🇨🇦",
  Canada: "🇨🇦",
  Brasil: "🇧🇷",
  Brazil: "🇧🇷",
  México: "🇲🇽",
  Mexico: "🇲🇽",
  España: "🇪🇸",
  Spain: "🇪🇸",
  Alemania: "🇩🇪",
  Germany: "🇩🇪",
  Francia: "🇫🇷",
  France: "🇫🇷",
  Italia: "🇮🇹",
  Uruguay: "🇺🇾",
  Colombia: "🇨🇴",
  Chile: "🇨🇱",
  Perú: "🇵🇪",
  Ecuador: "🇪🇨",
  Paraguay: "🇵🇾",
  Bolivia: "🇧🇴",
  Venezuela: "🇻🇪",
  Portugal: "🇵🇹",
  Inglaterra: "🇬🇧",
  England: "🇬🇧",
  Holanda: "🇳🇱",
  Netherlands: "🇳🇱",
  Bélgica: "🇧🇪",
  Belgium: "🇧🇪",
  Croacia: "🇭🇷",
  Croatia: "🇭🇷",
  Suiza: "🇨🇭",
  Switzerland: "🇨🇭",
  Japón: "🇯🇵",
  Japan: "🇯🇵",
  Corea: "🇰🇷",
  "South Korea": "🇰🇷",
  "Estados Unidos": "🇺🇸",
  "United States": "🇺🇸",
  Marruecos: "🇲🇦",
  Morocco: "🇲🇦",
  Senegal: "🇸🇳",
  Nigeria: "🇳🇬",
  Ghana: "🇬🇭",
  Camerún: "🇨🇲",
  "Costa Rica": "🇨🇷",
  Panamá: "🇵🇦",
  Panama: "🇵🇦",
  Honduras: "🇭🇳",
  Australia: "🇦🇺",
  Qatar: "🇶🇦",
  Egypt: "🇪🇬",
  Iran: "🇮🇷",
  "New Zealand": "🇳🇿",
  "Saudi Arabia": "🇸🇦",
  "Cape Verde": "🇨🇻",
  "Ivory Coast": "🇨🇮",
  Curacao: "🇨🇼",
  Curaçao: "🇨🇼",
  Tunisia: "🇹🇳",
  Algeria: "🇩🇿",
  Austria: "🇦🇹",
  Jordan: "🇯🇴",
  Uzbekistan: "🇺🇿",
  "South Africa": "🇿🇦",
  Scotland: "🇸🇨",
  Haiti: "🇭🇹",
  Norway: "🇳🇴",
  "Czech Republic": "🇨🇿",
  "Bosnia and Herzegovina": "🇧🇦",
  Turkey: "🇹🇷",
  Sweden: "🇸🇪",
  Iraq: "🇮🇶",
  "DR Congo": "🇨🇩",
  TBD: "❓",
  "Ganador A": "🏆",
  "Segundo B": "🥈",
  "Ganador QF1": "🏆",
  "Ganador QF2": "🏆",
  "Ganador SF1": "🏆",
  "Ganador SF2": "🏆",
  "Finalista 1": "🥇",
  "Finalista 2": "🥈",
};

export function getFlag(countryName: string): string {
  return COUNTRY_FLAGS[countryName] ?? "⚽";
}
